events {}

http {
    server {
        listen 80;

        location / {
            return 200 "o gateway do pai ta online e roteando\n";
            add_header Content-Type text/plain;
        }

        location /tarefas {
            proxy_pass http://tarefas:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /notificacao {
            proxy_pass http://notificacao:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /docs {
            proxy_pass http://tarefas:8001/docs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}